### ISSUE TITLE
Function Button

### ISSUE THREAD

**Issue by rmcguinness** [rmcguinness/WoodstockCodeCamp#27]
As a developer I will add a function button to handle all functions of the calculator for plus, minus, divide, and multiply in addition to the negative/positive function for changing the sign of the number and the equals sign for the final evaluation of the calculation.

The function operator MUST contain the logic to ensure multiple operators are not being applied to the equation. 

Errors during calculation SHOULD show "Err" in the display text and log what the error was in the console log. For example 10/0 should equal an Err with 'Divide by zero' showing in the console log files.

Lastly, I will apply the mathjs.org NPM package to simplify evaluation.

All buttons MUST contain an id and a key.

**Comment by JosMcG** [comment]
Also adding a clear button.
